freebsd_instance:
  image_family: freebsd-13-0-snap

task:
  name: FreeBSD 13.0
  env:
    IGNORE_OSVERSION: yes
  prerequisites_script:
    - pkg update -f
    - pkg upgrade -y
    - pkg install -y pkgconf vips node npm
  install_script:
    - npm install --build-from-source --unsafe-perm
  test_script:
    - npm test
