FROM resin/rpi-raspbian:jessie
MAINTAINER Lovell Fuller <npm@lovell.info>

# Build dependencies
RUN apt-get update && apt-get install -y build-essential autoconf libtool nasm gtk-doc-tools texinfo curl
